_extends: configu:.github/configs/release-drafter.yml
include-paths:
  - 'packages/formatters/'
name-template: 'formatters/v$RESOLVED_VERSION'
tag-template: 'formatters/v$RESOLVED_VERSION'
tag-prefix: 'formatters/'
