'@configu/repo':
  - '*' # Add 'repo' label to any root file changes

'@configu/cicd':
  - '.github/**'

'@configu/docs':
  - 'docs/**'

'@configu/examples':
  - 'examples/**'

'@configu/sdk':
  - 'packages/sdk/**'

'@configu/formatters':
  - 'packages/formatters/**'

'@configu/cli':
  - 'packages/cli/**'

'@configu/proxy':
  - 'packages/proxy/**'

'@configu/vscode':
  - 'packages/vscode/**'
