'@configu/repo':
  - '*' # Add 'repo' label to any root file changes

'@configu/cicd':
  - '.github/**'

'@configu/docs':
  - 'docs/**'

'@configu/examples':
  - 'examples/**'

'@configu/ts':
  - 'packages/ts/**'
  - 'packages/node/**'
  - 'packages/browser/**'

'@configu/lib':
  - 'packages/lib/**'

'@configu/cli':
  - 'packages/cli/**'

'@configu/vscode':
  - 'packages/vscode/**'
