packages:
  - 'packages/*'
  - 'packages/stores/*'
  - 'docs'

# https://pnpm.io/settings#cli-settings
engineStrict: true
packageManagerStrictVersion: true
managePackageManagerVersions: false

# https://pnpm.io/settings#build-settings
childConcurrency: 10
verifyDepsBeforeRun: warn

# https://pnpm.io/settings#nodejs-settings
useNodeVersion: 22.18.0

# https://pnpm.io/settings#workspace-settings
injectWorkspacePackages: true
disallowWorkspaceCycles: true

# https://pnpm.io/settings#other-settings
useStderr: true
updateNotifier: true
shellEmulator: true
