packages:
  - 'packages/*'
  - 'packages/stores/*'
  - 'docs'

# catalog:
#   'lodash': '^4.17.21'
#   '@types/lodash': '^4.17.20'
#   'validator': '^13.15.15'
#   '@types/validator': '^13.15.2'
#   '@configu/sdk': '^1.2.1'
#   '@configu/formatters': '^1.1.0'

# https://pnpm.io/settings#cli-settings
engineStrict: true
packageManagerStrictVersion: true
managePackageManagerVersions: false

# https://pnpm.io/settings#build-settings
childConcurrency: 10
verifyDepsBeforeRun: error

# https://pnpm.io/settings#nodejs-settings
useNodeVersion: 22.18.0

# https://pnpm.io/settings#workspace-settings
injectWorkspacePackages: true
disallowWorkspaceCycles: true

# https://pnpm.io/settings#other-settings
useStderr: true
updateNotifier: true
shellEmulator: true
