# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push
# https://docs.github.com/en/rest/using-the-rest-api/github-event-types#pushevent
name: Get release information
description: Extract release information from the pushed tag

outputs:
  package:
    description: Release package
    value: ${{ steps.release.outputs.package }}
  package_name:
    description: Release package
    value: ${{ steps.release.outputs.package_name }}
  package_path:
    description: Release package
    value: ${{ steps.release.outputs.package_path }}
  sha:
    description: Release sha
    value: ${{ steps.release.outputs.sha }}
  branch:
    description: Release branch
    value: ${{ steps.release.outputs.branch }}
  tag:
    description: Release tag
    value: ${{ steps.release.outputs.tag }}
  version:
    description: Release version
    value: ${{ steps.release.outputs.version }}
  channel:
    description: Release channel
    value: ${{ steps.release.outputs.channel }}

runs:
  using: composite
  steps:
    - name: Extract release information
      id: release
      shell: bash
      run: |
        sha=$(git rev-parse --short HEAD)

        ref_tag=${{ github.event.ref }}
        ref_branch=${{ github.event.base_ref }}

        tag=${ref_tag#refs/tags/}
        branch=${ref_branch#refs/heads/}

        package=$(echo "$tag" | awk -F '/v' '{print $1}')
        package_name=@configu/$package
        package_path=packages/$package

        version=$(echo "$tag" | awk -F '/v' '{print $2}')

        ref_channel=$(echo "$version" | awk -F '-' '{print $2}')
        if [ "next" = "${ref_channel%.*}" ]; then
          channel=next
        elif [ "$branch" = "${{ github.event.repository.master_branch }}" ]; then
          channel=latest
        else
          echo "couldn't resolve release channel based on the pushed tag"
          echo "use <package>/v<X.Y.Z>          for "latest" channel"
          echo "use <package>/v<X.Y.Z>-next.<I> for "next"   channel"
          exit 1
        fi

        echo "package: $package"
        echo "package_name: $package_name"
        echo "package_path: $package_path"
        echo "sha: $sha"
        echo "branch: $branch"
        echo "tag: $tag"
        echo "version: $version"
        echo "channel: $channel"

        echo "package=$package" >> $GITHUB_OUTPUT
        echo "package_name=$package_name" >> $GITHUB_OUTPUT
        echo "package_path=$package_path" >> $GITHUB_OUTPUT
        echo "sha=$sha" >> $GITHUB_OUTPUT
        echo "branch=$branch" >> $GITHUB_OUTPUT
        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "channel=$channel" >> $GITHUB_OUTPUT
