# todo: consider contributing this to the pnpm/action-setup repo by updating the GitHub Action one and reorder page
# https://pnpm.io/continuous-integration#github-actions
name: TypeScript environment setup
description: Setup Node.js and install dependencies

inputs:
  dependencies:
    description: Whether to run pnpm install
    required: true
    default: 'true'
  architecture:
    description: Force the architecture of pnpm install
    required: false

outputs:
  node_version:
    description: Node.js version
    value: ${{ steps.node.outputs.node_version }}
  node_path:
    description: Node.js installation path
    value: ${{ steps.node.outputs.node_path }}

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        # architecture: ${{ inputs.architecture }}
        node-version-file: '.node-version'
        cache: 'pnpm' # todo: https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
        registry-url: 'https://registry.npmjs.org'
        scope: '@configu'

    - name: Set Node.js information
      id: node
      shell: bash
      run: |
        node -v
        node_version=$(node -e 'console.log(process.versions.node)')
        node_path=$(node -e 'console.log(process.argv[0])')
        echo "node_version: $node_version"
        echo "node_path: $node_path"
        echo "node_version=$node_version" >> $GITHUB_OUTPUT
        echo "node_path=$node_path" >> $GITHUB_OUTPUT

    - name: Install dependencies
      if: ${{ inputs.dependencies == 'true' }} # * there is a bug in gh-actions causing booleans to be strings in composite actions - see: https://github.com/actions/runner/issues/1483#issuecomment-1042393939
      shell: bash
      run: |
        pnpm install --config.architecture=${{ inputs.architecture }}
        pnpm list --recursive --depth 0
      env:
        HUSKY: '0'
