# todo: consider contributing this to the pnpm/action-setup repo by updating the GitHub Action one and reorder page
# https://pnpm.io/continuous-integration#github-actions
name: TypeScript environment setup
description: Setup Node.js and install dependencies

inputs:
  install-dependencies:
    description: Runs pnpm install in the dependencies-root directory
    required: true
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'pnpm' # todo: currently cache is not working properly, try https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
        registry-url: 'https://registry.npmjs.org'
        scope: '@configu'

    - name: Install dependencies
      shell: bash
      if: ${{ inputs.install-dependencies == 'true' }} # * there is a bug in gh-actions causing booleans to be strings in composite actions - see: https://github.com/actions/runner/issues/1483#issuecomment-1042393939
      run: |
        pnpm install
        pnpm list --recursive --depth 0
      env:
        HUSKY: '0'
