name: "Python environment setup"
description: ""
inputs:
  python-version:
    description: "Python Version"
    required: true
    default: "3.9.16"
  poetry-version:
    description: "Poetry Version"
    required: true
    default: "1.4"
  install-dependencies:
    description: "Should install deps"
    required: true
    default: "true"
  dependencies-root:
    description: "Runs poetry install in this directory"
    required: true
    default: "py"

runs:
  using: "composite"
  steps:
    - name: Install Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry ${{ inputs.poetry-version }}
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ inputs.poetry-version }}

    - name: Set CWD environment variable
      shell: bash
      run: |
        echo "CWD=${{ inputs.dependencies-root }}" >> $GITHUB_ENV

    - name: Install dependencies
      shell: bash
      if: ${{ inputs.install-dependencies == 'true' }} # * there is a bug in gh-actions causing booleans to be strings in composite actions - see: https://github.com/actions/runner/issues/1483#issuecomment-1042393939
      run: |
        cd ${{ env.CWD }}
        poetry install
