name: "Monorepo environment setup"

inputs:
  node-version:
    description: "Node.js version"
    required: true
    default: "16.x"
  npm-version:
    description: "npm version"
    required: true
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Install Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"
        scope: "@configu"

    - name: Install npm latest
      shell: bash
      run: |
        npm install -g npm@${{ inputs.npm-version }}
        npm -v

    - name: Install npm dependencies
      shell: bash
      run: |
        npm install
        npm list --depth 0

    - name: Create local bin dir
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin
        echo "LOCAL_BIN=$HOME/.local/bin" >> $GITHUB_ENV
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - uses: robinraju/release-downloader@v1.5
      with:
        repository: "jsontypedef/json-typedef-codegen"
        latest: true
        fileName: "x86_64-unknown-linux-gnu.zip"

    - name: Append jtd-codegen to PATH # * https://www.scivision.dev/github-actions-path-append/
      shell: bash
      run: |
        unzip -d $LOCAL_BIN x86_64-unknown-linux-gnu.zip
