name: Deployment start hook
description: Run pre deployment tasks

inputs:
  slack-webhook:
    description: The Slack webhook URL
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/get-release-action
      id: release

    - name: Post Slack release notice
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.slack-webhook }}
        webhook-type: incoming-webhook
        payload: |
          text: "*${{ steps.release.outputs.tag }}* is now being released\n${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"

    - name: Create local bin dir
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin
        echo "LOCAL_BIN=$HOME/.local/bin" >> $GITHUB_ENV
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    # - uses: robinraju/release-downloader@v1.5
    #   with:
    #     repository: 'jsontypedef/json-typedef-codegen'
    #     latest: true
    #     fileName: 'x86_64-unknown-linux-gnu.zip'

    # - name: Append jtd-codegen to PATH # * https://www.scivision.dev/github-actions-path-append/
    #   shell: bash
    #   run: |
    #     unzip -d $LOCAL_BIN x86_64-unknown-linux-gnu.zip
