name: "Go environment setup"

inputs:
  go-version:
    description: "Node.js version"
    required: true
    default: "^1.20.6"
  npm-version:
    description: "npm version"
    required: true
    default: "latest"
  install-dependencies:
    required: true
    default: "true"
  dependencies-root:
    description: "Runs go install in this directory"
    required: true
    default: "go"

runs:
  using: "composite"
  steps:
    - name: Install Go ${{ inputs.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
    - name: Set CWD environment variable
      shell: bash
      run: |
        echo "CWD=${{ inputs.dependencies-root }}" >> $GITHUB_ENV
    - name: Install dependencies
      shell: bash
      if: ${{ inputs.install-dependencies == 'true' }} # * there is a bug in gh-actions causing booleans to be strings in composite actions - see: https://github.com/actions/runner/issues/1483#issuecomment-1042393939
      run: |
        cd ${{ env.CWD }}
        go install
