name: Build Deferred Integrations

on: workflow_dispatch

env:
  PACKAGE_NAME: 'configu-integrations'
  PACKAGE_PATH: 'packages/integrations'
  VERSION: 'latest'

jobs:
  #  start-release:
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - name: Checkout code
  #        uses: actions/checkout@v3
  #
  #      - uses: ./.github/actions/deploy-start-action
  #        id: deployment
  #        with:
  #          package-name: ${{ env.PACKAGE_NAME }}
  #          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ./.github/actions/ts-env-action

      - name: Build the integrations
        run: pnpm build:integrations

      - uses: actions/upload-artifact@master
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ matrix.os }}
          path: ${{ env.PACKAGE_PATH }}/dist
  end-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: ${{ env.PACKAGE_NAME }}-ubuntu-latest
          path: ${{ env.PACKAGE_PATH }}/dist
      - uses: actions/download-artifact@master
        with:
          name: ${{ env.PACKAGE_NAME }}-macos-latest
          path: ${{ env.PACKAGE_PATH }}/dist/latest
      - uses: actions/download-artifact@master
        with:
          name: ${{ env.PACKAGE_NAME }}-windows-latest
          path: ${{ env.PACKAGE_PATH }}/dist/latest

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          prerelease: true
          name: integrations
          tag_name: ${{ env.VERSION }}
          files: |
            ${{ env.PACKAGE_PATH }}/dist/latest/**/*

#      - uses: ./.github/actions/deploy-end-action
#        if: always()
#        with:
#          package-name: ${{ env.PACKAGE_NAME }}
#          package-version: ${{ steps.deployment.outputs.release-version }}
#          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
