name: CD/@configu/proxy

on:
  push:
    tags:
      - 'proxy/v*'

jobs:
  cd-proxy:
    name: CD/@configu/proxy
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: 'configu/proxy'
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy-start-action
        id: deployment
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: ./.github/actions/get-release-action
        id: release

      # todo: consider use this action to set tags
      # - uses: docker/metadata-action@v5
      #   id: meta
      #   with:
      #     images: name/app

      - name: Set Node.js information
        id: node
        shell: bash
        run: |
          node_version=$(cat .node-version)
          echo "node_version: $node_version"
          echo "node_version=$node_version" >> $GITHUB_OUTPUT

      # https://github.com/docker/build-push-action/tree/v6/?tab=readme-ov-file#examples
      # https://docs.docker.com/build/ci/github-actions/multi-platform/
      - uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release package to Docker Hub
        uses: docker/build-push-action@v6
        with:
          file: ${{ steps.release.outputs.package_path }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.release.outputs.version }}
            ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.release.outputs.channel }}
          build-args: |
            NODE_VERSION=${{ steps.node.outputs.node_version }}
          push: true
          provenance: true
          sbom: true

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.DOCKER_IMAGE_NAME }}
          short-description: Containerized Configu Proxy
          readme-filepath: ${{ steps.release.outputs.package_path }}/README.md
          enable-url-completion: true
      # ---
      - uses: ./.github/actions/deploy-end-action
        if: always()
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
