name: "CD/@configu/vscode"

on:
  push:
    tags:
      - vscode/v*

jobs:
  cd-vscode:
    name: "CD/@configu/vscode"
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: "vscode"
      PACKAGE_PATH: "packages/vscode"
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/deploy-start-action
        id: deployment
        with:
          package-name: ${{ env.PACKAGE_NAME }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: ./.github/actions/ts-env-action

      - uses: ./.github/actions/ts-env-action
        with:
          dependencies-root: "ts"
      # ---
      - name: Bump package version
        run: |
          cd ${{ env.CWD }}
          npm --no-git-tag-version version ${{ steps.deployment.outputs.release-version }} \
            --workspace=${{ env.PACKAGE_NAME }}

      - name: Build extension
        run: |
          cd ${{ env.CWD }}
          npm run build \
            --workspace=${{ env.PACKAGE_NAME }}

      - name: Upload vsix artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ steps.deployment.outputs.release-version }}
          path: ${{ env.CWD }}/${{ env.PACKAGE_PATH }}/build/${{ env.PACKAGE_NAME }}-${{ steps.deployment.outputs.release-version }}.vsix
          if-no-files-found: error

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            ${{ env.CWD }}/${{ env.PACKAGE_PATH }}/build/${{ env.PACKAGE_NAME }}-${{ steps.deployment.outputs.release-version }}.vsix

      # todo: Remove commented workflow after it decided to publish the extension to the market place
      # Reference https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions
      # - name: Publish to VSCode extension marketplace
      #   run: npm exec --workspace=${{ env.PACKAGE_NAME }} vsce publish -p ${{secrets.VSCE_PAT}}
      # ---
      - uses: ./.github/actions/deploy-end-action
        if: always()
        with:
          package-name: ${{ env.PACKAGE_NAME }}
          package-version: ${{ steps.deployment.outputs.release-version }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
