name: "CI/Go"

on:
  pull_request:
    branches:
      - main
    paths:
      - "go/**"

jobs:
  ci-go:
    name: "CI/Go"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ts-env-action

      - uses: ./.github/actions/go-env-action

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ${{ env.CWD }}
          args: --exclude "Error return value of \`.*\` is not checked"

      - name: Run Tests
        run: |
          cd ${{ env.CWD }}
          go test ./...
