name: "CI: Go Tests"
on:
  pull_request:
    branches:
      - main
    paths:
      - "go/**"

jobs:
  ci:
    name: Lint and Test
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/go-env-action

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ${{ env.CWD }}
          args: --exclude "Error return value of \`.*\` is not checked"

      - name: Run Tests
        run: |
          cd ${{ env.CWD }}
          go test ./...
