name: "CI/Python"

on:
  pull_request:
    branches:
      - main
    paths:
      - "py/**"

jobs:
  ci-python:
    name: "CI/Python"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ts-env-action

      - uses: ./.github/actions/py-env-action

      - name: Run black
        run: |
          cd ${{ env.CWD }}
          poetry run black configu

      - name: Run flake8
        run: |
          cd ${{ env.CWD }}
          poetry run flake8 configu

      - name: Run Tests
        run: |
          cd ${{ env.CWD }}
          poetry run pytest
