name: "CI/TypeScript"

on:
  pull_request:
    branches:
      - main
    paths:
      - "ts/packages/ts/**"
      - "ts/packages/node/**"
      - "ts/packages/browser/**"

jobs:
  ci-typescript:
    name: "CI/TypeScript"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ts-env-action

      - uses: ./.github/actions/ts-env-action
        with:
          dependencies-root: "ts"

      - name: Run formatter
        run: |
          cd ${{ env.CWD }}
          npm run format:check

      - name: Run linter
        run: |
          cd ${{ env.CWD }}
          npm run lint:check

      - name: Run tests & Generate coverage report
        run: |
          cd ${{ env.CWD }}
          npm run test:cov

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
      #   if: ${{ github.event_name == 'push' }}
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     flags: unittests
      #     fail_ci_if_error: true
      #     verbose: true
